global using Amazon.SimpleEmailV2;
global using Azure.Communication.Email;
global using Xunit;
global using Zaabee.Aws.SimpleEmail;
global using Zaabee.Azure.Email;
global using Zaabee.Email.Abstractions;
global using Zaabee.MailKit;
global using Zaabee.SmtpClient;
global using EmailAddress = Zaabee.Email.Abstractions.Models.EmailAddress;
global using EmailAttachment = Zaabee.Email.Abstractions.Models.EmailAttachment;
global using EmailContent = Zaabee.Email.Abstractions.Models.EmailContent;
global using EmailRecipients = Zaabee.Email.Abstractions.Models.EmailRecipients;
